# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        ref: master
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Checkout Pinger Repository
      run: git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/TassadarDC/Norbert.git pinger-src

    - name: Install Allure
      run: |
          sudo apt update
          sudo apt install -y allure

    - name: Install Go & Build `pinger`
      run: |
        sudo apt-get update && sudo apt-get install -y golang
        cd pinger-src
        GOOS=linux GOARCH=amd64 go build -o pinger main.go
        chmod +x pinger
        mv pinger ../src/main/resources/

    - name: Verify `pinger` Exists
      run: ls -lah src/main/resources/
     
    - name: Check `pinger` Format
      run: file src/main/resources/pinger
      
    - name: Run Tests
      run: mvn test -X
      continue-on-error: true
      
    - name: Check Maven Test Execution
      run: cat target/surefire-reports/*.txt || echo "No test reports found"

    - name: Debug Allure Results
      run: ls -R target || echo "target directory not found"
      
    - name: Generate Allure Report
      run: mvn allure:report

    - name: Check Allure Results Directory
      run: ls -la target/allure-results || echo "Directory not found"

    - name: Ensure Allure Results Directory
      run: mkdir -p target/allure-results
      
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/site/allure-maven/index.html
